[tools]
node = 'lts'
python = {version='3', virtualenv='.venv'}

[settings]
[alias.node]
my_custom_node = '20'  # makes `rtx install node@my_custom_node` install node-20.x
                       # this can also be specified in a plugin (see below in "Aliases")
