theme = "catppuccin_mocha"

[editor]
scrolloff = 15
line-number = "relative"
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true