[".config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]
    type = "file"
    url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-macchiato.toml"
    refreshPeriod = "168h"

[".config/bat/themes/Catppuccin-macchiato.tmTheme"]
    # Run "bat cache --build" to make the theme available
    type = "file"
    url = "https://github.com/catppuccin/bat/raw/main/Catppuccin-macchiato.tmTheme"
    refreshPeriod = "168h"
