#!/usr/bin/env bash

exclude="(scratch)" # exclude this entries, use regex: /(name1|name2)/

sesh connect "$(
	sesh list --hide-attached --icons |
		rg --invert-match "$exclude" | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind "tab:down,btab:up" \
		--bind "ctrl-a:change-prompt(⚡  )+reload(sesh list --hide-attached --icons | rg --invert-match '$exclude')" \
		--bind "ctrl-t:change-prompt(🪟  )+reload(sesh list -t --hide-attached --icons | rg --invert-match '$exclude')" \
		--bind "ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --hide-attached --icons | rg --invert-match '$exclude')" \
		--bind "ctrl-x:change-prompt(📁  )+reload(sesh list -z --hide-attached --icons | rg --invert-match '$exclude')" \
		--bind "ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)" \
		--bind "ctrl-d:execute(tmux kill-session -t {2})+change-prompt(⚡  )+reload(sesh list --hide-attached --icons | rg --invert-match '$exclude')"
)"
