import = ["/home/aleidk/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = false

[window]
decorations = "full"
dynamic_padding = true
opacity = 1

[window.padding]
x = 10
y = 10
