#!/usr/bin/env bash

echo -e "\n${BLD}${SUL}${GRN}Setting up ZSH...${RST}\n"

setup_zsh() {
  backup "$HOME/.zshenv"
  create "$HOME/.local/state/zsh/"
  symlink "$DOTS/config/zsh/zshrc" "$HOME"/.zshrc
  symlink "$DOTS/config/zsh/zprofile" "$HOME"/.zprofile
}

setup_zsh
