# Auto-generated aliases for Flatpak applications

alias junction='flatpak run re.sonny.Junction'
alias slack='flatpak run com.slack.Slack'
alias flatseal='flatpak run com.github.tchx84.Flatseal'
alias kid3='flatpak run org.kde.kid3'
alias client='flatpak run com.spotify.Client'
alias studio='flatpak run io.beekeeperstudio.Studio'
alias czkawka='flatpak run com.github.qarmin.czkawka'
alias detwinner='flatpak run com.neatdecisions.Detwinner'
alias guiscrcpy='flatpak run in.srev.guiscrcpy'
alias amberol='flatpak run io.bassi.Amberol'
alias pikabackup='flatpak run org.gnome.World.PikaBackup'
alias megasync='flatpak run nz.mega.MEGAsync'
alias celeste='flatpak run com.hunterwittenborn.Celeste'
alias boxes='flatpak run org.gnome.Boxes'
alias syncthingtk='flatpak run me.kozec.syncthingtk'
alias gdmsettings='flatpak run io.github.realmazharhussain.GdmSettings'
alias signal='flatpak run org.signal.Signal'
alias librewolf-community='flatpak run io.gitlab.librewolf-community'
alias browser='flatpak run com.brave.Browser'
alias jellyfin-media-player='flatpak run com.github.iwalton3.jellyfin-media-player'
alias compass='flatpak run com.mongodb.Compass'
alias postman='flatpak run com.getpostman.Postman'
alias obsidian='flatpak run md.obsidian.Obsidian'
alias spot='flatpak run dev.alextren.Spot'
alias insomnia='flatpak run rest.insomnia.Insomnia'
alias sequeler='flatpak run com.github.alecaddd.sequeler'
