# Auto-generated aliases for Flatpak applications

alias junction='flatpak run re.sonny.Junction'
alias slack='flatpak run com.slack.Slack'
alias flatseal='flatpak run com.github.tchx84.Flatseal'
alias kid3='flatpak run org.kde.kid3'
alias client='flatpak run com.spotify.Client'
alias studio='flatpak run io.beekeeperstudio.Studio'
alias czkawka='flatpak run com.github.qarmin.czkawka'
alias detwinner='flatpak run com.neatdecisions.Detwinner'
alias guiscrcpy='flatpak run in.srev.guiscrcpy'
alias amberol='flatpak run io.bassi.Amberol'
alias pikabackup='flatpak run org.gnome.World.PikaBackup'
alias megasync='flatpak run nz.mega.MEGAsync'
alias celeste='flatpak run com.hunterwittenborn.Celeste'
alias boxes='flatpak run org.gnome.Boxes'
alias syncthingtk='flatpak run me.kozec.syncthingtk'
alias gdmsettings='flatpak run io.github.realmazharhussain.GdmSettings'
alias signal='flatpak run org.signal.Signal'
alias librewolf-community='flatpak run io.gitlab.librewolf-community'
alias browser='flatpak run com.brave.Browser'
alias jellyfin-media-player='flatpak run com.github.iwalton3.jellyfin-media-player'
alias compass='flatpak run com.mongodb.Compass'
alias postman='flatpak run com.getpostman.Postman'
alias obsidian='flatpak run md.obsidian.Obsidian'
alias spot='flatpak run dev.alextren.Spot'
alias insomnia='flatpak run rest.insomnia.Insomnia'
alias sequeler='flatpak run com.github.alecaddd.sequeler'

# Auto-generated aliases for Flatpak applications

alias epiphany='flatpak run org.gnome.Epiphany'
alias font-viewer='flatpak run org.gnome.font-viewer'
alias eog='flatpak run org.gnome.eog'
alias clocks='flatpak run org.gnome.clocks'
alias baobab='flatpak run org.gnome.baobab'
alias weather='flatpak run org.gnome.Weather'
alias texteditor='flatpak run org.gnome.TextEditor'
alias nautiluspreviewer='flatpak run org.gnome.NautilusPreviewer'
alias maps='flatpak run org.gnome.Maps'
alias logs='flatpak run org.gnome.Logs'
alias extensions='flatpak run org.gnome.Extensions'
alias evince='flatpak run org.gnome.Evince'
alias contacts='flatpak run org.gnome.Contacts'
alias connections='flatpak run org.gnome.Connections'
alias characters='flatpak run org.gnome.Characters'
alias calendar='flatpak run org.gnome.Calendar'
alias calculator='flatpak run org.gnome.Calculator'
alias mediawriter='flatpak run org.fedoraproject.MediaWriter'
alias pods='flatpak run com.github.marhkb.Pods'
alias podmandesktop='flatpak run io.podman_desktop.PodmanDesktop'
