return {
	"stevearc/overseer.nvim",
	keys = {
		{ "<leader>pp", "<CMD>OverseerToggle<CR>", desc = "Toggle task runner" },
		{ "<leader>pr", "<CMD>OverseerRun<CR>", desc = "Run task" },
		{ "<leader>pf", "<CMD>OverseerQuickAction open float<CR>", desc = "Display current tasks" },
		{ "<leader>pm", "<CMD>OverseerTaskAction<CR>", desc = "Manage current tasks" },
	},
	opts = {
		task_list = {
			direction = "bottom",
			bindings = {
				["?"] = "ShowHelp",
				["g?"] = "ShowHelp",
				["<CR>"] = "RunAction",
				["<C-e>"] = "Edit",
				["o"] = "Open",
				["<C-v>"] = "OpenVsplit",
				["<C-s>"] = "OpenSplit",
				["<C-f>"] = "OpenFloat",
				["<C-q>"] = "OpenQuickFix",
				["<TAB>"] = "TogglePreview",
				["p"] = "TogglePreview",
				["<C-l>"] = "IncreaseAllDetail",
				["<C-h>"] = "DecreaseAllDetail",
				["L"] = "IncreaseDetail",
				["H"] = "DecreaseDetail",
				["["] = "DecreaseWidth",
				["]"] = "IncreaseWidth",
				["{"] = "PrevTask",
				["}"] = "NextTask",
				["<C-u>"] = "ScrollOutputUp",
				["<C-d>"] = "ScrollOutputDown",
				["q"] = "Close",
				["d"] = "<CMD>OverseerQuickAction dispose<CR>",
			},
		},
	},
}
